(function(){
'use strict';
var STORAGE_KEY='pcu-queue-lg-webos-settings-v1';
var defaults={serverBaseUrl:'http://192.168.1.100/display',apiPath:'api/queue-tv.php',hospitalName:'ระบบแสดงคิวผู้รับบริการ',hospitalSubtitle:'โรงพยาบาลส่งเสริมสุขภาพตำบล',displayDepartmentCount:3,pollIntervalMs:3000,statsIntervalMs:10000,voiceEnabled:true,announcePatientName:false,ttsRate:0.92,departments:[{code:'010',name:'จุดคัดกรอง',icon:'✚'},{code:'018',name:'ห้องตรวจโรค 1',icon:'⚕'},{code:'019',name:'ห้องตรวจโรค 2',icon:'▤'},{code:'030',name:'ห้องจ่ายยาผู้ป่วยนอก',icon:'💊'},{code:'040',name:'ห้องเจาะเลือด',icon:'◉'},{code:'050',name:'ห้องทันตกรรม',icon:'◇'}],notices:['กรุณาสวมหน้ากากอนามัยขณะรับบริการ','โปรดเตรียมบัตรประชาชนก่อนเข้ารับบริการ','กรุณารอฟังเสียงเรียกคิวจากระบบ'],marquee:'ยินดีต้อนรับเข้าสู่ระบบบริการอัตโนมัติ กรุณารอฟังเสียงเรียกคิวและติดตามหน้าจอแสดงผล'};
var settings=loadSettings(),currentQueues={},recentCalls=[],activeDepCode='',seenKeys=[],pollTimer=null,statsTimer=null,clearActiveTimer=null,pollBusy=false;
function el(id){return document.getElementById(id)}
function clone(o){return JSON.parse(JSON.stringify(o))}
function clamp(n,min,max){n=Number(n);if(!isFinite(n))return min;return Math.min(max,Math.max(min,n))}
function normalize(s){var out=clone(defaults),i;if(s){for(var k in s){if(Object.prototype.hasOwnProperty.call(s,k))out[k]=s[k]}}out.displayDepartmentCount=Math.round(clamp(out.displayDepartmentCount,1,6));out.pollIntervalMs=clamp(out.pollIntervalMs,1000,30000);out.statsIntervalMs=clamp(out.statsIntervalMs,3000,60000);out.ttsRate=clamp(out.ttsRate,.5,1.5);if(!out.departments||!out.departments.length)out.departments=clone(defaults.departments);for(i=0;i<6;i++){out.departments[i]=out.departments[i]||clone(defaults.departments[i]);if(!out.departments[i].icon)out.departments[i].icon=defaults.departments[i].icon}out.departments=out.departments.slice(0,6);return out}
function loadSettings(){try{var raw=localStorage.getItem(STORAGE_KEY);return normalize(raw?JSON.parse(raw):null)}catch(e){return clone(defaults)}}
function saveSettings(){localStorage.setItem(STORAGE_KEY,JSON.stringify(settings))}
function pad(n){return n<10?'0'+n:String(n)}
function thaiDate(d){var m=['มกราคม','กุมภาพันธ์','มีนาคม','เมษายน','พฤษภาคม','มิถุนายน','กรกฎาคม','สิงหาคม','กันยายน','ตุลาคม','พฤศจิกายน','ธันวาคม'];return d.getDate()+' '+m[d.getMonth()]+' '+(d.getFullYear()+543)}
function tick(){var d=new Date();el('clockTime').textContent=pad(d.getHours())+':'+pad(d.getMinutes())+':'+pad(d.getSeconds());el('clockDate').textContent=thaiDate(d)}
function formatQueue(v){if(v===undefined||v===null||v==='')return '-';var s=String(v).replace(/^\s+|\s+$/g,'');return /^\d+$/.test(s)&&s.length<3?('000'+s).slice(-3):s}
function visibleDepartments(){return settings.departments.slice(0,settings.displayDepartmentCount)}
function departmentName(item){var code=String(item.sd_queue_calling_curdep||'');for(var i=0;i<settings.departments.length;i++)if(settings.departments[i].code===code)return item.department||settings.departments[i].name;return item.department||code||'จุดบริการ'}
function renderHeader(){el('hospitalName').textContent=settings.hospitalName;el('hospitalSubtitle').textContent=settings.hospitalSubtitle;el('marqueeText').textContent=settings.marquee}
function renderQueues(){var grid=el('queueGrid'),deps=visibleDepartments(),html='',i,dep,item,active;grid.className='queue-grid count-'+deps.length;for(i=0;i<deps.length;i++){dep=deps[i];item=currentQueues[dep.code];active=dep.code&&dep.code===activeDepCode;html+='<div class="queue-card'+(active?' active':'')+'"><div class="card-icon left">'+(dep.icon||'✚')+'</div>'+(active?'<div class="card-icon right">🔊</div>':'')+'<div class="queue-number">'+formatQueue(item&&item.oqueue)+'</div><div class="service-name">'+escapeHtml(dep.name)+'</div><div class="dep-label">'+(dep.code?'DEP '+escapeHtml(dep.code):'ยังไม่กำหนด depcode')+'</div>'+(active?'<div class="calling-badge">กำลังเรียกคิว</div>':'')+'</div>'}grid.innerHTML=html}
function escapeHtml(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function renderAnnouncements(){var box=el('announceList'),html='',i,it;if(recentCalls.length){for(i=0;i<recentCalls.length&&i<6;i++){it=recentCalls[i];html+='<div class="announce-item"><div class="announce-left"><span class="announce-bullet">🔊</span><span>คิว '+formatQueue(it.oqueue)+' - '+escapeHtml(departmentName(it))+'</span></div><div class="announce-time">'+formatCallTime(it)+'</div></div>'}}else{for(i=0;i<settings.notices.length;i++)html+='<div class="announce-item"><div class="announce-left"><span class="announce-bullet">'+(i===0?'⚠':'ⓘ')+'</span><span>'+escapeHtml(settings.notices[i])+'</span></div></div>'}box.innerHTML=html}
function formatCallTime(it){var s=it.sd_queue_calling_datetime||'';var m=String(s).match(/(\d{2}):(\d{2}):(\d{2})/);if(m)return m[1]+':'+m[2]+':'+m[3];var d=new Date();return pad(d.getHours())+':'+pad(d.getMinutes())+':'+pad(d.getSeconds())}
function setConnection(state,msg){var p=el('connectionPill');p.className='connection-pill '+state;el('connectionText').textContent=state==='online'?'เชื่อมต่อแล้ว':state==='offline'?'ขาดการเชื่อมต่อ':'กำลังเชื่อมต่อ';if(state==='offline'){el('connectionError').textContent=msg||'เชื่อมต่อ Server ไม่สำเร็จ';el('connectionError').className='connection-error'}else el('connectionError').className='connection-error hidden'}
function activeDepcodes(s){var a=[],deps=s.departments.slice(0,s.displayDepartmentCount);for(var i=0;i<deps.length;i++)if(deps[i].code)a.push(deps[i].code);return a.join(',')}
function apiUrl(s){return String(s.serverBaseUrl).replace(/\/+$/,'')+'/'+String(s.apiPath).replace(/^\//,'')}
function postApi(s,params,cb){var xhr=new XMLHttpRequest(),body=[],k;for(k in params)if(Object.prototype.hasOwnProperty.call(params,k))body.push(encodeURIComponent(k)+'='+encodeURIComponent(params[k]));try{xhr.open('POST',apiUrl(s),true);xhr.timeout=8000;xhr.setRequestHeader('Content-Type','application/x-www-form-urlencoded; charset=UTF-8');xhr.onreadystatechange=function(){if(xhr.readyState!==4)return;if(xhr.status>=200&&xhr.status<300){try{cb(null,JSON.parse(String(xhr.responseText).replace(/^\uFEFF/,'')))}catch(e){cb(e)}}else cb(new Error('HTTP '+xhr.status))};xhr.ontimeout=function(){cb(new Error('timeout'))};xhr.onerror=function(){cb(new Error('network error'))};xhr.send(body.join('&'))}catch(e){cb(e)}}
function pollCalling(){if(pollBusy)return;var deps=activeDepcodes(settings);if(!deps)return;pollBusy=true;postApi(settings,{action:'calling',depcode:deps,limit:'6'},function(err,res){pollBusy=false;if(err||!res||res.success===false){setConnection('offline',err?err.message:(res&&res.message));return}setConnection('online');var q=res.queues||[];for(var i=0;i<q.length;i++)handleCall(q[i])})}
function pollStats(){var deps=activeDepcodes(settings);if(!deps)return;postApi(settings,{action:'stats',depcode:deps},function(err,res){if(!err&&res&&res.success&&res.stats){el('statTotal').textContent=Number(res.stats.totalvisit||0);el('statWaiting').textContent=Number(res.stats.waiting||0)}})}
function callKey(it){return [it.vn||'',it.sd_queue_calling_curdep||'',it.oqueue||'',it.sd_queue_calling_datetime||''].join('|')}
function handleCall(it){var code=String(it.sd_queue_calling_curdep||'');if(!code)return;currentQueues[code]=it;activeDepCode=code;var key=callKey(it),next=[it],i;for(i=0;i<recentCalls.length;i++)if(callKey(recentCalls[i])!==key)next.push(recentCalls[i]);recentCalls=next.slice(0,6);renderQueues();renderAnnouncements();if(clearActiveTimer)clearTimeout(clearActiveTimer);clearActiveTimer=setTimeout(function(){activeDepCode='';renderQueues()},12000);if(seenKeys.indexOf(key)>=0)return;seenKeys.push(key);if(seenKeys.length>100)seenKeys.shift();if(settings.voiceEnabled){var patient=settings.announcePatientName&&it.full_namecall?' '+it.full_namecall:'';speak('ขอเชิญหมายเลข '+formatQueue(it.oqueue)+patient+' เข้ารับบริการที่ '+departmentName(it)+' ค่ะ')}}
function browserSpeak(text){try{if(window.speechSynthesis&&window.SpeechSynthesisUtterance){var u=new SpeechSynthesisUtterance(text);u.lang='th-TH';u.rate=settings.ttsRate;u.pitch=1;window.speechSynthesis.cancel();window.speechSynthesis.speak(u)}}catch(e){}}
function speak(text){if(!text)return;try{if(window.webOS&&webOS.service&&webOS.service.request){webOS.service.request('luna://com.webos.service.tts',{method:'speak',parameters:{text:text},onSuccess:function(){},onFailure:function(){browserSpeak(text)}});return}}catch(e){}browserSpeak(text)}
function restartPolling(){if(pollTimer)clearInterval(pollTimer);if(statsTimer)clearInterval(statsTimer);pollCalling();pollStats();pollTimer=setInterval(pollCalling,settings.pollIntervalMs);statsTimer=setInterval(pollStats,settings.statsIntervalMs)}
function renderSettings(){el('sServer').value=settings.serverBaseUrl;el('sApiPath').value=settings.apiPath;el('sHospitalName').value=settings.hospitalName;el('sHospitalSubtitle').value=settings.hospitalSubtitle;el('sCount').value=settings.displayDepartmentCount;el('sPoll').value=settings.pollIntervalMs;el('sStatsPoll').value=settings.statsIntervalMs;el('sTtsRate').value=settings.ttsRate;el('sVoice').checked=!!settings.voiceEnabled;el('sPatient').checked=!!settings.announcePatientName;renderDepartmentRows(settings.departments);updateCountHint()}
function renderDepartmentRows(deps){var box=el('departmentRows'),html='',i;for(i=0;i<6;i++)html+='<div class="department-row"><div class="row-index">'+(i+1)+'</div><input class="dep-input focusable" data-index="'+i+'" data-field="code" maxlength="10" value="'+escapeHtml(deps[i].code)+'"><input class="name-input focusable" data-index="'+i+'" data-field="name" value="'+escapeHtml(deps[i].name)+'"></div>';box.innerHTML=html}
function updateCountHint(){el('countHint').textContent='ระบบจะแสดงลำดับที่ 1 ถึง '+Math.round(clamp(el('sCount').value,1,6))}
function openSettings(){renderSettings();el('testMessage').textContent='';el('settingsOverlay').className='settings-overlay';setTimeout(function(){el('sServer').focus()},50)}
function closeSettings(){el('settingsOverlay').className='settings-overlay hidden'}
function collectSettings(){var s=clone(settings),inputs=el('departmentRows').getElementsByTagName('input'),i,idx,field;s.serverBaseUrl=el('sServer').value;s.apiPath=el('sApiPath').value;s.hospitalName=el('sHospitalName').value;s.hospitalSubtitle=el('sHospitalSubtitle').value;s.displayDepartmentCount=Math.round(clamp(el('sCount').value,1,6));s.pollIntervalMs=clamp(el('sPoll').value,1000,30000);s.statsIntervalMs=clamp(el('sStatsPoll').value,3000,60000);s.ttsRate=clamp(el('sTtsRate').value,.5,1.5);s.voiceEnabled=el('sVoice').checked;s.announcePatientName=el('sPatient').checked;for(i=0;i<inputs.length;i++){idx=Number(inputs[i].getAttribute('data-index'));field=inputs[i].getAttribute('data-field');if(field)s.departments[idx][field]=inputs[i].value}return normalize(s)}
function applySettings(){settings=collectSettings();saveSettings();currentQueues={};recentCalls=[];activeDepCode='';renderHeader();renderQueues();renderAnnouncements();closeSettings();restartPolling()}
function testConnection(){var s=collectSettings();el('testMessage').textContent='กำลังทดสอบ...';postApi(s,{action:'health'},function(err,res){el('testMessage').textContent=err?'เชื่อมต่อไม่สำเร็จ: '+err.message:(res&&res.success===false?'API แจ้งข้อผิดพลาด':'เชื่อมต่อ Server/API สำเร็จ')})}
function resetSettings(){settings=clone(defaults);renderSettings();el('testMessage').textContent='คืนค่าเริ่มต้นแล้ว กด “บันทึกและใช้งาน” เพื่อยืนยัน'}
function isSettingsOpen(){return el('settingsOverlay').className.indexOf('hidden')<0}
function onKey(e){var code=e.keyCode||e.which||0;if(code===405){e.preventDefault();if(!isSettingsOpen())openSettings();return}if(code===461){e.preventDefault();if(isSettingsOpen())closeSettings();else{try{if(window.webOS&&webOS.platformBack)webOS.platformBack();else window.close()}catch(x){window.close()}}}}
function init(){renderHeader();renderQueues();renderAnnouncements();tick();setInterval(tick,1000);el('settingsBtn').onclick=openSettings;el('closeSettingsBtn').onclick=closeSettings;el('saveBtn').onclick=applySettings;el('testBtn').onclick=testConnection;el('resetBtn').onclick=resetSettings;el('sCount').onchange=updateCountHint;document.addEventListener('keydown',onKey,false);restartPolling()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
